#include <stdio.h>
#include <conio.h>
void main()
 {
 clrscr();
  int r, c, a[100][100], b[100][100], sum[100][100], i, j;
  printf("Enter the number of rows: ");
  scanf("%d", &r);
  printf("Enter the number of columns : ");
  scanf("%d", &c);

  printf("\nEnter elements of 1st matrix:\n");
  for (i = 0; i < r; i++)
    for (j = 0; j < c; j++)
    {
      printf("Enter element of a %d%d: ", i , j );
      scanf("%d", &a[i][j]);
    }

  printf("Enter elements of 2nd matrix:\n");
  for (i = 0; i < r; i++)
    for (j = 0; j < c; j++)
    {
      printf("Enter element of b %d%d: ", i , j );
      scanf("%d", &b[i][j]);
    }


  for (i = 0; i < r; i++)
    for (j = 0; j < c; j++)
    {
      sum[i][j] = a[i][j] + b[i][j];
    }


  printf("\nSum of two matrices: \n");
  for (i = 0; i < r; i++)
    for (j = 0; j < c; j++)
    {
      printf("%d   ", sum[i][j]);
      if (j == c - 1)
      {
	printf("\n\n");
    }
    }
 getch();
}
