    #include<stdio.h>
#include<conio.h>
#include<string.h>
void main()
{
 clrscr();
 int i,j,l;
 char n[100],n2[100];
 printf("Please, Enter the Word ");
 gets(n);
 l=strln(n);
 for(i=0;j=l-1;j<=1;i++;j--)
    {
      n[i]=n2[j];
    }
    n2[l]=n[l];
    }
    for(i=0;i<l;i++)
    {
    if(n2[i]==n[i])
    {
    c++
    }
    if(C==l)
    {
 printf("\nThe Number is palindrom);
    }
    else
    {
    printf("\nthe is not Palindrom")
    }
getch();
}